### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [Adaz99/portfolio-project#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements : DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE - Needs work

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 30 / 50  |
| Responsiveness       | 10 / 15  |
| Code Knowledge & Use | 10 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 5 / 10   |
| Total Score          | 65 / 110 |

## Positive

The website looks good, and almost matches the design. There are a couple of tweaks you will need to make mainly around spacing. Everything feels pretty squished so make use of padding and margin to add space between your html elements.

You are using semantic tags, keep this up. Your tags need to describe the contents they are holding. Not everything needs to be a `<div>` :).

You have focused on mobile first and have created a responsive website, that works on desktop & mobile. Good going!

As your first project I think this is a success considering you didn't have time for the pre-course. This is great!

The reason why your mark is slightly lower is because of the quality of the code, you are using SCSS but not all of the features it gives you. You are kinda using BEM but it is hit and miss. I will give you some pointers no worries.

## Constructive

- With your SCSS

  - You have a `_variables.scss` file which you do use in `_base.scss` but that is the only place. Try using the values in your `_components.scss` so if you do want to change something you can do it in one place.
  - You not making use of nesting. This will make your code easier to understand. You are grouping your styles into little blocks. I will give you demo of nesting below with the BEM points.

- With BEM try and keep it simple by grouping things.
  - It may seem strange to have a convention for naming styles but on big projects keeping things consistent is key.
  - You wouldn't use any html selectors to do any styling just the class names.
  - The class name should describe what it is, generally you wouldn't use the tag name in the class. Keep it descriptive

Lets compare HTML.

```html
<section id="Starting">
  <div class="StartingHeader">
    <div class="introText">
      <p class="StartingIntroP">Hello! I'm Airidas Sienauskas</p>
      <h1 class="StartingIntroH1">A Junior Cloud ☁️ Engineer based in London.</h1>
    </div>
    <div class="introPic">
      <img class="startingImg" src="./Images/Picture.png" alt="" />
    </div>
  </div>
</section>
<!-- THE CODE ABOVE WOULD PROBABLY BE -->
<!-- I HAVE RENAMED IT TO INTRO AS THAT IS WHAT IT IS -->
<section id="intro">
  <div class="intro__header">
    <div class="intro__titles">
      <p class="intro__text">Hello! I'm Airidas Sienauskas</p>
      <h1 class="intro__title">A Junior Cloud ☁️ Engineer based in London.</h1>
    </div>
    <div class="intro__image-container">
      <img class="intro__image" src="./Images/Picture.png" alt="" />
    </div>
  </div>
</section>
```

Lets compare SCSS, this includes nesting.

```scss
.startingImg {
  display: none;
}

.StartingHeader {
  margin-bottom: 40px;
}

.StartingIntroP {
  font-size: 1.25rem;
  margin: 40px;
}

.StartingIntroH1 {
  font-size: 4rem;
  align-self: center;
  margin: 40px 40px 40px 40px;
}

// WOULD BE

.intro {
  &__header {
    margin-bottom: 40px;
  }

  &__title {
    font-size: 4rem;
    align-self: center;
    margin: 40px 40px 40px 40px;
  }

  &__text {
    font-size: 1.25rem;
    margin: 40px;
  }

  &__image {
    display: none;
  }
}
```

I want you to take these points further with your next project, use SCSS and the awesome features it gives you. Try using BEM for naming as well.

Reach out if you do run into any problems.

---
